### PR TITLE
Feature/order by

### PR DESCRIPTION
**Pull request by rennerocha**
Adding order_by='<header_name>' parameter to Table.

### CODE REVIEW

**Comment by turicas** [comment]
Hello Renne, thanks for your help.

This test will fail in your implementation:

```
def test_ordering_numbers_as_strings(self):
    my_table = Table(headers=['spam'], order_by='spam')
    my_table.rows.append(['5'])
    my_table.rows.append([31])
    my_table.rows.append(['42'])
    self.assertEqual(str(my_table), dedent('''
    +------+
    | spam |
    +------+
    |   31 |
    |   42 |
    |    5 |
    +------+
    ''').strip())
```

Before ordering we should normalize data types. For example: if we have a mix of `int`, `str` and `float` in some column, all values should be converted to `str` **before** ordering. If all values are `int`, they will remain `int`; if some values are `float` and others `int`, convert all to `float`, and so on.

I've created a [method to identify data types in branch `feature/mysql`](https://github.com/turicas/outputty/commit/882c7eb88a1d2a96df832b0ddc54f9e75e27d43b) - I'll merge it to master soon; after that I'll merge your code and fix it (identify and convert data types before ordering).

**Comment by turicas** [comment]
I pushed your code + some fixes to [feature/orderby](https://github.com/turicas/outputty/tree/feature/order_by) but it still failing in one test (related to identify type of data before ordering).

I'll finish MySQL support and then will fix this test so we can merge it to master.

**Comment by rennerocha** [comment]
Your test is a little weird. Isn't the expected result of this table:

```
    +------+
    | spam |
    +------+
    |    5 |
    |   31 |
    |   42 |
    +------+
```

Instead of:

```
    +------+
    | spam |
    +------+
    |   31 |
    |   42 |
    |    5 |
    +------+
```

**Comment by turicas** [comment]
It depends on the way you trea the type of data. If do you think all the column values should be converted to strings, to the second way is the correct one. But if do you treat all this data as int, the first way is correct.

When using `Table(from_csv=...)` I think we should try to convert all columns to int, float etc. and try to discover the type of data (if we don't do this, all data will be treated as string), but actually I don't know what should be the less surprising thing about converting data directly from `my_table.rows.append(...)` - in this test we have strings and ints...what should we do before sorting?

**Comment by rennerocha** [comment]
I agree with you that the better way when we import data from a CSV file is try to "discover" the right data type, because it is very common that a column of int or floats to be represented as quoted strings instead of numbers.

But in the second case with `my_table.rows.append(...)`, I can think a third possible behaviour: one can expect the same as the sort method, ordering first numbers and then the strings:

```
>>> c = ['5', 61, '42']
>>> c.sort()
>>> c
[61, '42', '5']
```

I see three ways to solve this problem before sorting:
1. Try to convert the appended data to int/float (my favorite!);
2. Convert all appended data to string;
3. Let string and int mixed and order as the sort method.

What do you prefer?

**Comment by turicas** [comment]
I think you are right about letting Python sort when using `my_table.rows.append(...)` and only guess type when importing from CSV.

I think we could correct the problem about when using `my_table.rows.append(...)` and add support to asc|desc to merge this branch on master. Later, when I complete feature/mysql, we can add the feature of guessing data types when importing from CSV. What do you think?

**Pull request merged**
